#!/bin/bash
# Skript arvutab 10 esimese paarisarvu summa

#arvutab
summa=0
for (( i=2; i<=10; i+=2 )); do
  summa=$((summa + i))
done
#annab teada vahemiku summa
echo "Arvude vahemikus 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $summa"

