#!/bin/bash
# Skript kontrollib, kas 1-20 arvud on algarvud

#otsib
for (( arv=1; arv<=20; arv++ )); do
  onAlgarv=true
  if [ $arv -lt 2 ]; then
    onAlgarv=false
  else
    for (( i=2; i*i<=arv; i++ )); do
      if [ $((arv % i)) -eq 0 ]; then
        onAlgarv=false
        break
      fi
    done
  fi
#kas algarv on true
  if [ "$onAlgarv" = true ]; then
    echo "$arv on algarv"
  else
    echo "$arv ei ole algarv"
  fi
done

