#!/bin/bash
#Renee
#info
#skript tervitab ja ütleb praeguse kellaaja


# 1. Väljasta „Tere, “ ilma reavahetuseta
echo -n "Tere, "

# 2. Tekita kasutaja nimi vastava käsu kombinatsiooni(de) abil ning väljasta ta reavahetuseta
username=$(whoami)
echo -n "$(echo ${username^})"

# 3. Väljasta „!“ reavahetusega
echo "!"

echo "Täna on $(date +"%d.%m.%Y kell %H:%M")"
