#!/bin/bash
#sisend vanusest
echo -n "Sisesta oma vanus: "
read vanus
#kontrollib, mis vahemikkuse see jääb ja kui jääb vahemikku, siis prindib vastavalt sellele, mis vahele jäi
#Kui paned suurema, siis annab viimase. Kui paned negatiivse, siis prindib vigase sisendi
if [ $vanus -ge 0 -a $vanus -lt 11 ]; then
  echo "Oled laps"
elif [ $vanus -ge 11 -a $vanus -lt 18 ]; then
  echo "Oled nooruk"
elif [ $vanus -ge 18 -a $vanus -lt 63 ]; then
  echo "Oled täiskasvanu"
elif [ $vanus -ge 63 ]; then
  echo "Oled senjoor"
else
  echo "Vigane sisend"
fi

