#!/bin/bash
#võtab praeguse kellaja ja kasutajanime operatsioonsüsteemilt
aeg=$(date +"%H")
kasutaja=$(whoami)
#kontrollib, kas jääb vahedesse
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
  echo "Tere hommikust, $kasutaja!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
  echo "Tere päevast, $kasutaja!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
  echo "Tere õhtust, $kasutaja!"
else
  echo "Head ööd, $kasutaja!"
fi
