#!/bin/bash
# See skript tervitab kasutajat tema kasutajanimega

# 1. Väljasta „Tere, “ ilma reavahetuseta
echo -n "Tere, "

# 2. Tekita kasutaja nimi vastava käsu kombinatsiooni(de) abil ning väljasta ta reavahetuseta
username=$(whoami)
echo -n "$(echo ${username^})"

# 3. Väljasta „!“ reavahetusega
echo "!"
